---
services:
  front:
    build:
      context: ./
      dockerfile: front_Dockerfile
    hostname: front
    ports:
      - "8080:8080"
    working_dir: /etc/front
    command: npm run start
  api:
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: api_Dockerfile
    working_dir: /etc/api
    command: ./gradlew bootRun
version: "3"
