---
services:
  front:
    image: node:8.0.0
    hostname: front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/etc/front
    working_dir: /etc/front
    # command: npm start
    command: "sleep infinity"
  api:
    ports:
      - "3000:8080"
    build:
      context: ./
      dockerfile: api_Dockerfile
    volumes:
      - ./api:/etc/api
    working_dir: /etc/api
    # command: npm start
    command: "sleep infinity"
version: "3"
