---
services:
  front:
    image: node:8.0.0
    hostname: front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/etc/front
    working_dir: /etc/front
    command: "sleep infinity"
  api:
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: api_dev_Dockerfile
    volumes:
      - ./api:/etc/api
    working_dir: /etc/api
    command: "sleep infinity"
version: "3"
